# Generated by Django 4.2.1 on 2025-02-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs_analyze', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
